use tauri_build::{DefaultPermissionRule, InlinedPlugin};

fn main() {
    // Sadly, there is no better way to do it right now
    // You could try parsing source code here and detecting #[tauri::command]
    // But I think it's not worth it
    // https://github.com/tauri-apps/tauri/issues/10075
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .codegen(tauri_build::CodegenContext::new())
            .plugin(
                "auth",
                InlinedPlugin::new()
                    .commands(&[
                        "check_reachable",
                        "login",
                        "begin_yggdrasil_login",
                        "finish_yggdrasil_login",
                        "list_yggdrasil_saved_logins",
                        "get_yggdrasil_password",
                        "set_yggdrasil_password",
                        "delete_yggdrasil_password",
                        "add_offline_user",
                        "remove_user",
                        "get_default_user",
                        "set_default_user",
                        "get_users",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "cache",
                InlinedPlugin::new()
                    .commands(&[
                        "get_project",
                        "get_project_many",
                        "get_project_v3",
                        "get_project_v3_many",
                        "get_version",
                        "get_version_many",
                        "get_user",
                        "get_user_many",
                        "get_team",
                        "get_team_many",
                        "get_organization",
                        "get_organization_many",
                        "get_search_results",
                        "get_search_results_many",
                        "get_search_results_v3",
                        "get_search_results_v3_many",
                        "purge_cache_types",
                        "get_project_versions",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "content-search",
                InlinedPlugin::new()
                    .commands(&["resolve_chinese_content_search"])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "curseforge",
                InlinedPlugin::new()
                    .commands(&[
                        "curseforge_capability",
                        "curseforge_validate_credentials",
                        "curseforge_search_projects",
                        "curseforge_get_project",
                        "curseforge_get_projects",
                        "curseforge_get_description",
                        "curseforge_get_files",
                        "curseforge_get_file",
                        "curseforge_get_files_many",
                        "curseforge_get_changelog",
                        "curseforge_get_download_url",
                        "curseforge_get_categories",
                        "curseforge_match_fingerprints",
                        "curseforge_install_file",
                        "curseforge_update_installed_file",
                        "curseforge_recognize_instance_files",
                        "curseforge_install_modpack",
                        "curseforge_update_managed_modpack",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "import",
                InlinedPlugin::new()
                    .commands(&[
                        "get_importable_instances",
                        "import_instance",
                        "is_valid_importable_instance",
                        "get_default_launcher_path",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "jre",
                InlinedPlugin::new()
                    .commands(&[
                        "get_java_versions",
                        "set_java_version",
                        "jre_find_filtered_jres",
                        "jre_get_jre",
                        "jre_test_jre",
                        "jre_auto_install_java",
                        "jre_get_max_memory",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "logs",
                InlinedPlugin::new()
                    .commands(&[
                        "logs_get_logs",
                        "logs_get_logs_by_filename",
                        "logs_get_output_by_filename",
                        "logs_delete_logs",
                        "logs_delete_logs_by_filename",
                        "logs_get_latest_log_cursor",
                        "logs_get_live_log_buffer",
                        "logs_clear_live_log_buffer",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "metadata",
                InlinedPlugin::new()
                    .commands(&[
                        "metadata_get_game_versions",
                        "metadata_get_loader_versions",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "minecraft-skins",
                InlinedPlugin::new()
                    .commands(&[
                        "get_available_capes",
                        "get_available_skins",
                        "add_and_equip_custom_skin",
                        "equip_skin",
                        "remove_custom_skin",
                        "save_custom_skin",
                        "set_custom_skin_order",
                        "unequip_skin",
                        "flush_pending_skin_change",
                        "flush_pending_skin_change_for_profile",
                        "normalize_skin_texture",
                        "get_dragged_skin_data",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "mr-auth",
                InlinedPlugin::new()
                    .commands(&[
                        "modrinth_login",
                        "logout",
                        "get",
                        "cancel_modrinth_login",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "install",
                InlinedPlugin::new()
                    .commands(&[
                        "install_get_modpack_preview",
                        "install_create_instance",
                        "install_create_modpack_instance",
                        "install_import_instance",
                        "install_duplicate_instance",
                        "install_existing_instance",
                        "install_pack_to_existing_instance",
                        "install_job_list",
                        "install_job_get",
                        "install_job_retry",
                        "install_job_cancel",
                        "install_job_dismiss",
                        "install_job_support_details",
                        "download_job_list",
                        "download_job_get",
                        "download_job_retry",
                        "download_job_cancel",
                        "download_job_delete",
                        "download_history_clear",
                        "download_job_support_details",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "process",
                InlinedPlugin::new()
                    .commands(&[
                        "process_get_all",
                        "process_get_by_instance_id",
                        "process_kill",
                        "process_wait_for",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "instance",
                InlinedPlugin::new()
                    .commands(&[
                        "instance_remove",
                        "instance_get",
                        "instance_get_many",
                        "instance_get_projects",
                        "instance_get_installed_project_ids",
                        "instance_get_install_candidates",
                        "instance_content",
                        "instance_get_content_items",
                        "instance_get_dependencies_as_content_items",
                        "instance_get_linked_modpack_info",
                        "instance_get_linked_modpack_content",
                        "instance_get_optimal_jre_key",
                        "instance_get_full_path",
                        "instance_get_mod_full_path",
                        "instance_list",
                        "instance_check_installed",
                        "instance_update_all",
                        "instance_update_project",
                        "instance_add_project_from_version",
                        "instance_install_project_with_dependencies",
                        "instance_switch_project_version_with_dependencies",
                        "instance_add_project_from_path",
                        "instance_toggle_disable_project",
                        "instance_remove_project",
                        "instance_update_managed_modrinth_version",
                        "instance_repair_managed_modrinth",
                        "instance_run",
                        "instance_kill",
                        "instance_edit",
                        "instance_cache_icon",
                        "instance_edit_icon",
                        "instance_export_mrpack",
                        "instance_get_pack_export_candidates",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "settings",
                InlinedPlugin::new()
                    .commands(&[
                        "settings_get",
                        "settings_set",
                        "download_source_health",
                        "reset_download_source_health",
                        "cancel_directory_change",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "tags",
                InlinedPlugin::new()
                    .commands(&[
                        "tags_get_categories",
                        "tags_get_report_types",
                        "tags_get_loaders",
                        "tags_get_game_versions",
                        "tags_get_donation_platforms",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "translation",
                InlinedPlugin::new()
                    .commands(&[
                        "translation_get_settings",
                        "translation_update_settings",
                        "translation_set_secret",
                        "translation_test_provider",
                        "translation_translate",
                        "translation_clear_cache",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "shortcuts",
                InlinedPlugin::new()
                    .commands(&["create_instance_shortcut"])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "utils",
                InlinedPlugin::new()
                    .commands(&[
                        "get_os",
                        "is_network_metered",
                        "should_disable_mouseover",
                        "highlight_in_folder",
                        "open_path",
                        "show_launcher_logs_folder",
                        "show_app_db_backups_folder",
                        "progress_bars_list",
                        "get_opening_command",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "files",
                InlinedPlugin::new()
                    .commands(&[
                        "file_extract_zip",
                        "file_save_as",
                        "file_read_dragged_file",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            )
            .plugin(
                "worlds",
                InlinedPlugin::new()
                    .commands(&[
                        "get_recent_worlds",
                        "get_instance_worlds",
                        "get_singleplayer_world",
                        "set_world_display_status",
                        "rename_world",
                        "reset_world_icon",
                        "backup_world",
                        "delete_world",
                        "add_server_to_instance",
                        "edit_server_in_instance",
                        "remove_server_from_instance",
                        "get_instance_protocol_version",
                        "get_server_status",
                        "start_join_singleplayer_world",
                        "start_join_server",
                    ])
                    .default_permission(
                        DefaultPermissionRule::AllowAllCommands,
                    ),
            ),
    )
    .expect("Failed to run tauri-build");
}
